version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
  revive:
    rules:
      - name: exported
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gci:
    sections:
      - standard
      - default
      - prefix(e-commerce-go)